---
# tasks file for playbook/roles/nginx
- name: Install
  become: yes
  apt:
    name: nginx
    state: latest
- name: Service
  become: yes
  service:
    name: nginx
    state: started
    enabled: true
- name: Supprimer defaultconf
  become: yes
  file: 
    path: /etc/nginx/sites-enabled/default 
    state: absent
  notify: nginx reload

- name: "site"
  include: site.yml
  with_items: "{{ domains }}"
